[package]
name = "AdventOfCode2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
itertools = "0.9.0"
im = "15.0.0"